apiVersion: v1
kind: Service
metadata:
  name: students-exam-scores-service
spec:
  selector:
    app: students-exam-scores
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
